### ISSUE TITLE
Game crash when leaning

### ISSUE THREAD

**Issue by deko0** [offyerrocker/PD2-TacticalLeaning#2]
Anytime i try to lean, my game crashes. All of my mods are updated, and the mod used to work until yesterday, when i opened the game after not playing for a while and it started crashing. 

This is the crash text:

-------------------------------

Application has crashed: C++ exception
[string "lib/units/cameras/fpcameraplayerbase.lua"]:331: attempt to perform arithmetic on field 'absolute_progress' (a nil value)

SCRIPT STACK

lib/units/cameras/fpcameraplayerbase.lua:195

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlGetCurrentDirectory_U                            
         payday2_win32_release  (???)     ???                                                 
                         ntdll  (???)     RtlAllocateHeap                                     
         payday2_win32_release  (???)     ???           
                                               
-------------------------------

I've never reported an issue before so i don't really know if this is enough.

**Comment by offyerrocker** [comment]
Thanks for the report!
Looks like you have an old version of the mod - I believe this issue was fixed in v3.0.
You can verify this by checking the mod version in-game or in the mod.txt/main.xml files- the current version is 3.3, and you likely have v2.1. Update the mod and this problem should be fixed.
Anything before v3.0 probably doesn't have auto-updating enabled since the paydaymods site went down, so you'll need to get it manually from this GitHub repo or from [the ModWorkshop page](https://modworkshop.net/mod/22254) (they should both have the latest version).

**Comment by deko0** [comment]
well that's embarassing. yep, i had 2.1, thought it updated with the auto updater, thanks for telling me
